services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,ses,lambda
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
